print("jangan lupa makan ya")
print("jangan lupa bernafas ya")
print("jangan lupa minum kawan")
print("jangan lupa nonton upin ipin ya")
print("jangan lupa untuk selalu membahagiakan orang tua")
print("jangan pernah putus asa ya kawan")
print("jangan pernah melawan orang tua")
print("jangan pernah melupakan kenangan yang pernah ada")
print("jangan pernah memakai barang terlarang")
print("jangan pernah kamu jadi wibu hahaha")